{
 "title": "Fossil",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Command", "query": "APPEND,QUERY" }
  ]
 },
 "panels": [
  {
   "title": "$Command throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(fossil_response_ns_count{container=\"fossil\", cmd=\"$Command\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Routines Exist",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{container=\"fossil\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Routines Live",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_sched_goroutines_goroutines{container=\"fossil\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "fossil_client_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Counts by Cmd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cmd) (fossil_requests{container=\"fossil\"})",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Sched latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 3 },
   "targets": [
    {
     "expr": "rate(go_sched_latencies_seconds_sum{container=\"fossil\"}[$__rate_interval])/rate(go_sched_latencies_seconds_count{container=\"fossil\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"fossil\", container=\"fossil\"}",
     "legendFormat": "k8s_usage"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{container=\"fossil\"}[$__rate_interval])",
     "legendFormat": "go_alloc"
    }
   ]
  },
  {
   "title": "$Command response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(fossil_response_ns_sum{cmd=\"$Command\", container=\"fossil\"}[$__rate_interval]) / rate(fossil_response_ns_count{cmd=\"$Command\", container=\"fossil\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gc Pauses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "rate(go_gc_pauses_seconds_sum{container=\"fossil\"}[$__rate_interval])/rate(go_gc_pauses_seconds_count{container=\"fossil\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container=\"fossil\"}[$__rate_interval]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response time [$Command]",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(fossil_response_ns_bucket{cmd=\"$Command\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(fossil_response_ns_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(fossil_response_ns_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fossil_response_ns_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fossil_database_segments{container=\"fossil\"}",
     "legendFormat": "Segments"
    },
    {
     "expr": "fossil_database_topics{container=\"fossil\"}",
     "legendFormat": "Topics"
    }
   ]
  }
 ]
}