apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fossil-data-pvc
  namespace: fossil
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 128Mi
