apiVersion: v1
kind: Service
metadata:
  name: fossil
  labels:
    app: fossil
spec:
  selector:
    app: fossil
  ports:
  - port: 8001
    targetPort: 8001
    name: tcp
  - port: 2112
    targetPort: 2112
    name: http
